pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    // environment { 
    //     GREETING = 'Hello Jenkins'
    // }
    options {
        ansiColor('xterm')
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        
    }
   parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
   }
    //build
    stages {
        stage('Init') { 
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure
                """
            }
        }
        stage('Plan') { 
            steps {
                sh """
                    cd 01-vpc
                    terraform plan
                """
            }
        }
        stage('Deploy') { 
            when {
                expression {
                    "${params.action}" == 'apply' 
                }
            }
            input {
                message "Should we continue?"
                ok "yes, we should."
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                """    
            }
        }
      
    }
    //post build
    post {
        always {
            echo " I will always say Hello again"
        }
        failure { 
            echo 'this runs when pipeline is failed, used generally to send some alerts'
        }
        success{
            echo 'I will say Hello when pipeline is success'
        }
    }
}